// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdWc9-LY4vHreIbKu01E1dmtirTcKJ_0',
    appId: '1:416572123259:web:dae8393938f0642cd9dade',
    messagingSenderId: '416572123259',
    projectId: 'miraiurjavi',
    authDomain: 'miraiurjavi.firebaseapp.com',
    storageBucket: 'miraiurjavi.firebasestorage.app',
    measurementId: 'G-D7Q1C4XYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsi7ul-heCtCLEqGGIzwXsgPtl6nD3pD4',
    appId: '1:416572123259:android:767eac39664fd3bed9dade',
    messagingSenderId: '416572123259',
    projectId: 'miraiurjavi',
    storageBucket: 'miraiurjavi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYRx_V09LxuM5Xfc3fepUIt6p3An5e8M',
    appId: '1:416572123259:ios:58f54a67857913b9d9dade',
    messagingSenderId: '416572123259',
    projectId: 'miraiurjavi',
    storageBucket: 'miraiurjavi.firebasestorage.app',
    iosBundleId: 'com.example.miraiurjaviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYRx_V09LxuM5Xfc3fepUIt6p3An5e8M',
    appId: '1:416572123259:ios:58f54a67857913b9d9dade',
    messagingSenderId: '416572123259',
    projectId: 'miraiurjavi',
    storageBucket: 'miraiurjavi.firebasestorage.app',
    iosBundleId: 'com.example.miraiurjaviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdWc9-LY4vHreIbKu01E1dmtirTcKJ_0',
    appId: '1:416572123259:web:cbb59e46046579add9dade',
    messagingSenderId: '416572123259',
    projectId: 'miraiurjavi',
    authDomain: 'miraiurjavi.firebaseapp.com',
    storageBucket: 'miraiurjavi.firebasestorage.app',
    measurementId: 'G-CEF2LZ0XZ1',
  );
}
